"""Long-run regression, Engle-Granger cointegration and ECM estimation."""
from __future__ import annotations

import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller

from .config import (
    DATA_PROCESSED,
    EXOG_DIFF_COLUMNS,
    EXOG_LOG_COLUMNS,
    OUTPUT_MODELS,
    OUTPUT_TABLES,
    ensure_directories,
)


def load_processed_data(path=DATA_PROCESSED) -> pd.DataFrame:
    """Load processed data generated by src.data_process."""
    return pd.read_csv(path)


def fit_long_run_model(df: pd.DataFrame):
    """Estimate the long-run log-level OLS model."""
    y = df["LNY"]
    x = sm.add_constant(df[EXOG_LOG_COLUMNS])
    return sm.OLS(y, x, missing="drop").fit()


def cointegration_residual_adf(residual: pd.Series) -> pd.DataFrame:
    """Run an ADF test on the long-run residual for EG cointegration."""
    stat, pvalue, lags, nobs, critical_values, icbest = adfuller(
        residual.dropna(), regression="n", autolag="AIC"
    )
    return pd.DataFrame(
        [
            {
                "test": "ADF on long-run residual",
                "adf_stat": stat,
                "p_value": pvalue,
                "lags": lags,
                "nobs": nobs,
                "critical_1pct": critical_values.get("1%"),
                "critical_5pct": critical_values.get("5%"),
                "critical_10pct": critical_values.get("10%"),
                "icbest": icbest,
            }
        ]
    )


def fit_ecm(df: pd.DataFrame):
    """Estimate the Error Correction Model.

    ECM_L1 is the one-period lag of the residual from the long-run model.
    """
    working = df.copy()
    long_run = fit_long_run_model(working)
    working["ECM"] = long_run.resid
    working["ECM_L1"] = working["ECM"].shift(1)

    model_df = working.dropna(subset=["DLNY", *EXOG_DIFF_COLUMNS, "ECM_L1"]).copy()
    y = model_df["DLNY"]
    x = sm.add_constant(model_df[[*EXOG_DIFF_COLUMNS, "ECM_L1"]])
    ecm = sm.OLS(y, x).fit()
    return ecm, long_run, working, model_df


def coefficients_table(result) -> pd.DataFrame:
    """Convert a statsmodels result object to a tidy coefficient table."""
    table = pd.DataFrame(
        {
            "variable": result.params.index,
            "coef": result.params.values,
            "std_error": result.bse.values,
            "t_stat": result.tvalues.values,
            "p_value": result.pvalues.values,
            "ci_lower": result.conf_int()[0].values,
            "ci_upper": result.conf_int()[1].values,
        }
    )
    return table


def export_model_outputs(df: pd.DataFrame | None = None) -> dict[str, object]:
    """Fit models and export coefficient tables and text summaries."""
    ensure_directories()
    if df is None:
        df = load_processed_data()

    ecm, long_run, working, model_df = fit_ecm(df)

    coefficients_table(long_run).to_csv(
        OUTPUT_TABLES / "long_run_coefficients.csv", index=False, encoding="utf-8-sig"
    )
    coefficients_table(ecm).to_csv(
        OUTPUT_TABLES / "ecm_coefficients.csv", index=False, encoding="utf-8-sig"
    )
    cointegration_residual_adf(working["ECM"]).to_csv(
        OUTPUT_TABLES / "cointegration_residual_adf.csv", index=False, encoding="utf-8-sig"
    )
    working.to_csv(OUTPUT_TABLES / "model_working_data.csv", index=False, encoding="utf-8-sig")

    (OUTPUT_MODELS / "long_run_summary.txt").write_text(long_run.summary().as_text(), encoding="utf-8")
    (OUTPUT_MODELS / "ecm_summary.txt").write_text(ecm.summary().as_text(), encoding="utf-8")

    return {"ecm": ecm, "long_run": long_run, "working": working, "model_df": model_df}


def main() -> None:
    outputs = export_model_outputs()
    print("=== Long-run OLS model ===")
    print(outputs["long_run"].summary())
    print("\n=== Error Correction Model ===")
    print(outputs["ecm"].summary())


if __name__ == "__main__":
    main()
